"use client";
import { useEffect, useState } from "react";
import { Button, Input, Table } from "@heroui/react";
import { CirclePlayFill, CircleStop, Pencil, Plus } from "@gravity-ui/icons";
import OperationPageHeader from "../../../components/OperationPageHeader";
import { useOperation } from "../../../components/OperationProvider";
import { operationJson, operationRequest } from "../../../lib/operation-api";
import type { Customer, Order } from "../../../lib/operation-types";
import { DataPanel, DataTable, IconAction, ModalShell, StatStrip, StatusChip } from "../../../components/OperationUi";
export default function CustomersPage() { const { refresh, refreshToken } = useOperation(); const [customers, setCustomers] = useState<Customer[]>([]); const [orders, setOrders] = useState<Order[]>([]); const [selected, setSelected] = useState<Customer | null | undefined>(undefined); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); async function load() { setLoading(true); const results = await Promise.all([operationRequest<Customer[]>("/api/customers"), operationRequest<Order[]>("/api/orders")]).catch(() => null); if (!results || results.some((result) => !result.response.ok || !result.payload.data)) setError("客户数据读取失败"); else { setCustomers(results[0].payload.data!); setOrders(results[1].payload.data!); } setLoading(false); } useEffect(() => { void load(); }, [refreshToken]); async function toggle(item: Customer) { await operationJson(`/api/customers/${encodeURIComponent(item.customerId)}/status`, { status: item.status === "active" ? "inactive" : "active" }); refresh(); } return <><OperationPageHeader eyebrow="CUSTOMER MANAGEMENT" title="客户管理" description="沉淀客户档案、联系人和合作状态。" loading={loading} onRefresh={refresh} actions={<Button onPress={() => setSelected(null)}><Plus className="h-4 w-4" />新增客户</Button>} />{error ? <p className="mb-4 text-sm text-danger">{error}</p> : null}<StatStrip items={[{ label: "客户总数", value: customers.length }, { label: "合作中", value: customers.filter((item) => item.status === "active").length }, { label: "已停用", value: customers.filter((item) => item.status === "inactive").length }, { label: "关联订单", value: orders.length }]} /><DataPanel title="客户档案" note={`${customers.length} 家客户`}><DataTable label="客户档案" empty="暂无客户，请先创建客户档案。" columns={["客户", "联系人", "联系方式", "订单", "状态", "操作"]}>{customers.map((item) => <Table.Row key={item.customerId} id={item.customerId}><Table.Cell>{item.name}</Table.Cell><Table.Cell>{item.contactName || "-"}</Table.Cell><Table.Cell>{item.contactPhone || item.contactEmail || "-"}</Table.Cell><Table.Cell>{orders.filter((order) => order.customerId === item.customerId).length} 笔</Table.Cell><Table.Cell><StatusChip status={item.status} /></Table.Cell><Table.Cell><div className="flex"><IconAction label="编辑" onPress={() => setSelected(item)}><Pencil /></IconAction><IconAction label={item.status === "active" ? "停用" : "启用"} onPress={() => void toggle(item)}>{item.status === "active" ? <CircleStop /> : <CirclePlayFill />}</IconAction></div></Table.Cell></Table.Row>)}</DataTable></DataPanel>{selected !== undefined ? <CustomerModal customer={selected} onClose={() => setSelected(undefined)} onSaved={refresh} /> : null}</>; }
function CustomerModal({ customer, onClose, onSaved }: { customer: Customer | null; onClose: () => void; onSaved: () => void }) { const [form, setForm] = useState({ name: customer?.name || "", contactName: customer?.contactName || "", contactPhone: customer?.contactPhone || "", contactEmail: customer?.contactEmail || "", notes: customer?.notes || "" }); async function save() { await operationJson(customer ? `/api/customers/${encodeURIComponent(customer.customerId)}` : "/api/customers", form); onClose(); onSaved(); } return <ModalShell title={customer ? "编辑客户" : "新增客户"} onClose={onClose}><form className="space-y-3" onSubmit={(event) => { event.preventDefault(); void save(); }}>{Object.entries(form).map(([key, value]) => <Input key={key} aria-label={key} placeholder={key} value={value} onChange={(event) => setForm({ ...form, [key]: event.currentTarget.value })} required={key === "name"} />)}<Button type="submit">保存客户</Button></form></ModalShell>; }
