"use client";
import { useEffect, useState } from "react";
import { Table, TextArea } from "@heroui/react";
import { Eye } from "@gravity-ui/icons";
import OperationPageHeader from "../../../components/OperationPageHeader";
import { useOperation } from "../../../components/OperationProvider";
import { operationJson, operationRequest } from "../../../lib/operation-api";
import type { License, Order } from "../../../lib/operation-types";
import { ConfirmAction, DataPanel, DataTable, formatDate, IconAction, ModalShell, StatusChip } from "../../../components/OperationUi";
export default function LicensesPage() { const { refresh, refreshToken } = useOperation(); const [licenses, setLicenses] = useState<License[]>([]); const [orders, setOrders] = useState<Order[]>([]); const [selected, setSelected] = useState<License | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); async function load() { setLoading(true); const results = await Promise.all([operationRequest<License[]>("/api/licenses"), operationRequest<Order[]>("/api/orders")]).catch(() => null); if (!results || results.some((result) => !result.response.ok || !result.payload.data)) setError("许可证数据读取失败"); else { setLicenses(results[0].payload.data!); setOrders(results[1].payload.data!); } setLoading(false); } useEffect(() => { void load(); }, [refreshToken]); async function destroy(id: string) { const { response, payload } = await operationJson(`/api/licenses/${encodeURIComponent(id)}/destroy`); if (!response.ok) setError(payload.message || "许可证销毁失败"); else refresh(); } return <><OperationPageHeader eyebrow="LICENSE MANAGEMENT" title="许可证签发" description="查看订单交付的平台模块与 AI 员工授权。" loading={loading} onRefresh={refresh} />{error ? <p className="mb-4 text-sm text-danger">{error}</p> : null}<DataPanel title="许可证列表" note={`${licenses.length} 份许可证`}><DataTable label="许可证列表" empty="暂无许可证。" columns={["客户", "关联订单", "签发时间", "有效至", "状态", "操作"]}>{licenses.map((item) => { const legacy = item.linkageStatus === "legacy_unlinked"; return <Table.Row key={item.licenseId} id={item.licenseId}><Table.Cell>{item.customerNameSnapshot || item.subject}</Table.Cell><Table.Cell>{legacy ? "历史无订单" : orders.find((order) => order.orderId === item.orderId)?.orderNo || "订单已不存在"}</Table.Cell><Table.Cell>{formatDate(item.issuedAt)}</Table.Cell><Table.Cell>{formatDate(item.expiresAt)}</Table.Cell><Table.Cell><StatusChip status={legacy ? "legacy_unlinked" : item.platformStatus} /></Table.Cell><Table.Cell><div className="flex gap-1"><IconAction label="查看更多" onPress={() => setSelected(item)}><Eye /></IconAction>{!legacy && item.platformStatus !== "destroyed" ? <ConfirmAction label="销毁许可证" danger onConfirm={() => void destroy(item.licenseId)} /> : null}</div></Table.Cell></Table.Row>; })}</DataTable></DataPanel>{selected ? <ModalShell title="许可证详情" onClose={() => setSelected(null)}><p className="mb-2">许可证 ID：{selected.licenseId}</p><p className="mb-2">模块：{selected.modules.join("、") || "无"}</p><p className="mb-2">AI 员工：{selected.aiEmployees.map((item) => item.title).join("、") || "无"}</p><TextArea aria-label="完整许可证" className="min-h-80 font-mono text-xs" value={selected.license} readOnly /></ModalShell> : null}</>; }
