"use client";
import { ReactNode, useState } from "react";
import { Button, Card, Chip, Modal, Table, Tooltip } from "@heroui/react";
import { AlertDialog } from "@heroui/react/alert-dialog";
export const formatDate = (value?: number) => value ? new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value * 1000)) : "-";
export const formatMoney = (cents = 0) => new Intl.NumberFormat("zh-CN", { style: "currency", currency: "CNY" }).format(cents / 100);
const labels: Record<string, string> = { active: "启用", inactive: "停用", pending_payment: "待回款", paid: "已回款", fulfilled: "已交付", cancelled: "已取消", running: "运行中", expired: "已过期", destroyed: "已销毁", approved: "已通过", pending_review: "待审核", rejected: "已驳回", legacy_unlinked: "历史无订单" };
export function StatusChip({ status }: { status: string }) { return <Chip size="sm" color={["active", "paid", "fulfilled", "running", "approved"].includes(status) ? "success" : ["expired", "destroyed", "rejected"].includes(status) ? "danger" : "default"} variant="soft">{labels[status] || status}</Chip>; }
export function StatStrip({ items }: { items: Array<{ label: string; value: ReactNode }> }) { return <div className="mb-4 grid grid-cols-2 gap-3 lg:grid-cols-4">{items.map((item) => <Card key={item.label} className="p-4"><span className="text-xs text-muted">{item.label}</span><strong className="mt-2 block text-xl">{item.value}</strong></Card>)}</div>; }
export function DataPanel({ title, note, children, actions }: { title: string; note: string; children: ReactNode; actions?: ReactNode }) { return <Card className="mb-4"><div className="flex flex-wrap items-center justify-between gap-3 px-4 py-3"><div><h2 className="text-sm font-semibold">{title}</h2><p className="mt-0.5 text-xs text-muted">{note}</p></div>{actions}</div>{children}</Card>; }
export function DataTable({ label, columns, children, empty }: { label: string; columns: string[]; children: ReactNode; empty: string }) { return <Table><Table.ScrollContainer className="overflow-x-auto"><Table.Content aria-label={label} className="min-w-[720px]"><Table.Header>{columns.map((column, index) => <Table.Column key={column} id={column} isRowHeader={index === 0}>{column}</Table.Column>)}</Table.Header><Table.Body renderEmptyState={() => <div className="p-10 text-center text-sm text-muted">{empty}</div>}>{children}</Table.Body></Table.Content></Table.ScrollContainer></Table>; }
export function IconAction({ label, children, onPress }: { label: string; children: ReactNode; onPress: () => void }) { return <Tooltip><Tooltip.Trigger><Button isIconOnly size="sm" variant="ghost" aria-label={label} onPress={onPress}>{children}</Button></Tooltip.Trigger><Tooltip.Content>{label}</Tooltip.Content></Tooltip>; }
export function ConfirmAction({ label, children, onConfirm, danger = false }: { label: string; children?: ReactNode; onConfirm: () => void; danger?: boolean }) { const [open, setOpen] = useState(false); return <><Button size="sm" variant={danger ? "danger-soft" : "ghost"} onPress={() => setOpen(true)}>{children || label}</Button><AlertDialog isOpen={open} onOpenChange={setOpen}><AlertDialog.Backdrop><AlertDialog.Container placement="center" size="sm"><AlertDialog.Dialog><AlertDialog.Header><AlertDialog.Heading>{label}</AlertDialog.Heading></AlertDialog.Header><AlertDialog.Body>确认执行此操作吗？</AlertDialog.Body><AlertDialog.Footer><Button variant="ghost" onPress={() => setOpen(false)}>取消</Button><Button variant={danger ? "danger" : "primary"} onPress={() => { setOpen(false); onConfirm(); }}>确认</Button></AlertDialog.Footer></AlertDialog.Dialog></AlertDialog.Container></AlertDialog.Backdrop></AlertDialog></>; }
export function ModalShell({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <Modal isOpen onOpenChange={(open) => !open && onClose()}><Modal.Backdrop isDismissable><Modal.Container placement="center" scroll="inside" size="lg"><Modal.Dialog><Modal.Header><Modal.Heading>{title}</Modal.Heading><Modal.CloseTrigger aria-label="关闭" /></Modal.Header><Modal.Body className="p-5">{children}</Modal.Body></Modal.Dialog></Modal.Container></Modal.Backdrop></Modal>; }
